name: Firebase

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      NUXT_ENV_SENTRY_DNS: ${{ secrets.SENTRY_DNS }}
      NUXT_ENV_SEO_URL: ${{ secrets.SEO_URL }}
      NUXT_ENV_SEO_TWITTER_IMAGE: ${{ secrets.SEO_TWITTER_IMAGE }}
      NUXT_ENV_SEO_TWITTER_ACCOUNT: ${{ secrets.SEO_TWITTER_ACCOUNT }}

    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITE_NOGSANTOS }}'
          channelId: live
          projectId: site-nogsantos
