name: Tests

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests Stage
    steps:
      - uses: actions/checkout@v2
      - name: Install and test
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm i
      - run: npm run test
